# Generated by Django 5.0.2 on 2024-06-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contact_delete_contactmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="full_name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=50),
        ),
    ]
